name: WGTreeFarmFlag
version: 0.1
description: '"WorldGuard" extension to add own region flags to plants and protects saplings where a tree gets destroyed and to block block placement inside of these regions even for op/canbuild.'
author: BangL
depend: [WorldGuard, WorldEdit, WGCustomFlags]
main: de.bangl.wgtff.WGTreeFarmFlagPlugin
