name: WGTreeFarmFlag
version: 0.2
description: '"WorldGuard" extension to add own region flags to plants and protects saplings where a tree gets destroyed and to block block placement inside of these regions even for op/canbuild.'
author: BangL, mewin
depend: [ WorldGuard, WGCustomFlags ]
softdepend: [ WGBlockRestricter ]
main: de.bangl.wgtff.WGTreeFarmFlagPlugin
